-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local configs = os.getenv("HOME") .. "/.config/hypr/configs" -- Default Configs directory path

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- Always refer to Hyprland wiki
-- https://wiki.hyprland.org/

-- Initial boot script enable to apply initial wallpapers, theming, new settings etc.
-- suggest not to change this or delete this including deleting referrence file in ~/.config/hypr/.initial_startup_done
-- as long as the referrence file is present, this initial-boot.sh will not execute

--## Sourcing external config files ###

-- Source: ~/.config/hypr/configs/ENVariables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.ENVariables")
-- Source: ~/.config/hypr/configs/Keybinds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.Keybinds")

-- Load defaults, then user additions/overrides
-- Source: ~/.config/hypr/configs/Startup_Apps.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.Startup_Apps")

-- For laptop related
-- Source: ~/.config/hypr/configs/Laptops.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.Laptops")

-- Load defaults, then user additions
-- Source: ~/.config/hypr/configs/WindowRules.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.WindowRules")

-- Source: ~/.config/hypr/configs/SystemSettings.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.SystemSettings")
-- Source: ~/.config/hypr/configs/Animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.Animations")

-- Source: ~/.config/hypr/configs/Borders.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("configs.Borders")

-- nwg-displays
-- Source: ~/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")
-- Source: ~/.config/hypr/workspaces.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("workspaces")

hl.on("hyprland.start", function()
	hl.exec_cmd("$HOME/.config/hypr/initial-boot.sh")
end)
