-- Generated by nwg-displays on 2026-05-02 at 23:59:55. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "3840x2400@60.0",
    position = "0x0",
    scale = "2.13",
})

