-- Generated by nwg-displays on 2026-01-23 at 12:43:29. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true,
})

hl.workspace_rule({
    workspace = "6",
    monitor = "eDP-1",
})

