# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F5F7FB
background         #141414
cursor             #838686

active_tab_foreground     #141414
active_tab_background     #F5F7FB
inactive_tab_foreground   #F5F7FB
inactive_tab_background   #141414

active_border_color   #F5F7FB
inactive_border_color #141414
bell_border_color     #0D100D

color0      #3B3C3B
color1		#0D100D
color2		#0D100D
color3		#294531
color4		#364650
color5		#596D7E
color6		#AAAFB7
color7		#E8ECF1
color8		#A2A5A9
color9		#121511
color10		#121511
color11		#365C41
color12		#485D6A
color13		#7791A8
color14		#E2E9F4
color15		#E8ECF1
