# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EBD6F9
background         #131415
cursor             #A08BB1

active_tab_foreground     #131415
active_tab_background     #EBD6F9
inactive_tab_foreground   #EBD6F9
inactive_tab_background   #131415

active_border_color   #EBD6F9
inactive_border_color #131415
bell_border_color     #15151D

color0      #3A3B3C
color1		#15151D
color2		#3F304F
color3		#373F4C
color4		#72518B
color5		#AA4F4E
color6		#9568B3
color7		#DABCEE
color8		#9984A7
color9		#1B1B26
color10		#544069
color11		#4A5465
color12		#986DB9
color13		#E26968
color14		#C68AEE
color15		#DABCEE
