# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FCF2E5
background         #18191B
cursor             #AC9D98

active_tab_foreground     #18191B
active_tab_background     #FCF2E5
inactive_tab_foreground   #FCF2E5
inactive_tab_background   #18191B

active_border_color   #FCF2E5
inactive_border_color #18191B
bell_border_color     #14181D

color0      #3E4042
color1		#14181D
color2		#463739
color3		#785655
color4		#4C6462
color5		#7F5A58
color6		#B8A388
color7		#F2E4D2
color8		#A99F93
color9		#1B2026
color10		#5D494B
color11		#9F7271
color12		#658582
color13		#A97876
color14		#F6D9B6
color15		#F2E4D2
