-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local edit = "${EDITOR:-vim}"
local term = "kitty" -- Terminal
local files = "thunar" -- File Manager
local Search_Engine = "\"https://www.google.com/search?q={}\""

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- Environment variables. See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("EDITOR", "nvim")

hl.env("HL_GPU_DEVICE", "0")

--## Toolkit Backend Variables ###
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("CLUTTER_BACKEND", "wayland")

--## XDG Specifications ###
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")

--## QT Variables ###
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

--## hyprland-qt-support ###
hl.env("QT_QUICK_CONTROLS_STYLE", "org.hyprland.style")

--## xwayland apps scale fix (useful if you are use monitor scaling) ###
-- Set same value if you use scaling in Monitors.conf
-- 1 is 100% 1.5 is 150%
-- see https://wiki.hyprland.org/Configuring/XWayland/
hl.env("GDK_SCALE", "2")
hl.env("QT_SCALE_FACTOR", "1")

-- Bibata-Modern-Ice-Cursor
-- NOTE! You must have the hyprcursor version to activate this.
-- https://wiki.hyprland.org/Hypr-Ecosystem/hyprcursor/
hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")

-- Zoom stuff
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")

hl.env("LIBVA_DRIVER_NAME", "radeonsi")

--### Hyprland Environment Variables ####
-- https://wiki.hyprland.org/Configuring/Environment-variables/#hyprland-environment-variables
-- env = HYPRLAND_TRACE,1 # Enables more verbose logging.
-- env = HYPRLAND_NO_RT,1 # Disables realtime priority setting by Hyprland.
-- env = HYPRLAND_NO_SD_NOTIFY,1 # If systemd, disables the 'sd_notify' calls.
-- env = HYPRLAND_NO_SD_VARS,1 # Disables management of variables in systemd and dbus activation environments.
