-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"
local scriptsDir = os.getenv("HOME") .. "/.config/hypr/scripts"
local rofiPath = os.getenv("HOME") .. "/.config/hypr/rofi/config.rasi"

-- -----------------------------------------------------
-- 🚀 APPLICATIONS & LAUNCHERS
-- -----------------------------------------------------
hl.bind(
	"ALT + SPACE",
	hl.dsp.exec_cmd(
		"pkill rofi || true && rofi -show drun -modi drun,filebrowser,run,window -config ~/.config/hypr/rofi/config.rasi"
	),
	{ description = "app launcher" }
)
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(term), { description = "Open terminal" })
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(files), { description = "file manager" })
hl.bind(
	mainMod .. " + B",
	hl.dsp.exec_cmd('env ELECTRON_OZONE_PLATFORM_HINT=wayland xdg-open "https://"'),
	{ description = "open default browser" }
)
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("obsidian"), { description = "Obsidian" })
hl.bind(
	mainMod .. " + X",
	hl.dsp.exec_cmd("brave-browser --app-id=hnpfjngllnobngcgfapefoaidbinmjnm"),
	{ description = "WhatsApp" }
)
hl.bind("F12", hl.dsp.exec_cmd("rog-control-center"), { description = "Open the G-Helper Equiv" })

-- -----------------------------------------------------
-- 📋 FEATURES / EXTRAS
-- -----------------------------------------------------
hl.bind(
	mainMod .. " + SHIFT + SLASH",
	hl.dsp.exec_cmd(scriptsDir .. "/KeyHints.sh"),
	{ description = "help / cheat sheet" }
)
hl.bind(
	mainMod .. " + ALT + R",
	hl.dsp.exec_cmd(scriptsDir .. "/Refresh.sh"),
	{ description = "refresh bar and menus" }
)
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd(scriptsDir .. "/RofiEmoji.sh"), { description = "emoji menu" })
hl.bind(mainMod .. " + S", hl.dsp.exec_cmd(scriptsDir .. "/RofiSearch.sh"), { description = "web search" })
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(scriptsDir .. "/ClipManager.sh"), { description = "clipboard manager" })
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd(scriptsDir .. "/RofiCalc.sh"), { description = "calculator" })
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(scriptsDir .. "/WallpaperSelect.sh"), { description = "select wallpaper" })
hl.bind("CTRL + ALT + W", hl.dsp.exec_cmd(scriptsDir .. "/WallpaperRandom.sh"), { description = "random wallpaper" })
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd(scriptsDir .. "/RofiBeats.sh"), { description = "online music" })
hl.bind(mainMod .. " + SLASH", hl.dsp.exec_cmd(scriptsDir .. "/KeyBinds.sh"), { description = "search keybinds" })
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd(scriptsDir .. "/OverviewToggle.sh"), { description = "desktop overview" })

-- -----------------------------------------------------
-- 🪟 WINDOW MANAGEMENT
-- -----------------------------------------------------
hl.bind(mainMod .. " + Q", hl.dsp.window.close(), { description = "close active window" })
hl.bind(mainMod .. " + SHIFT + Q", function()
	local win = hl.get_active_window()
	if win and win.pid then
		os.execute("kill -9 " .. tostring(win.pid))
	end
end, { description = "Terminate active process natively" })
hl.bind(mainMod .. " + SPACE", hl.dsp.window.float({ action = "toggle" }), { description = "Float current window" })
hl.bind(
	mainMod .. " + ALT + SPACE",
	hl.dsp.exec_cmd("hyprctl dispatch workspaceopt allfloat"),
	{ description = "Float all windows" }
)
hl.bind(
	mainMod .. " + SHIFT + F",
	hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }),
	{ description = "fullscreen" }
)
hl.bind(
	mainMod .. " + F",
	hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }),
	{ description = "maximize window" }
)
hl.bind(
	mainMod .. " + O",
	hl.dsp.window.set_prop({ prop = "opaque", value = "toggle", window = "active" }),
	{ description = "toggle active window opacity" }
)
hl.bind(
	mainMod .. " + grave",
	hl.dsp.exec_cmd(scriptsDir .. "/Dropterminal.sh $term"),
	{ description = "DropDown terminal" }
)

-- -----------------------------------------------------
-- 🎯 FOCUS & NAVIGATION
-- -----------------------------------------------------
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }), { description = "focus left" })
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }), { description = "focus right" })
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }), { description = "focus up" })
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }), { description = "focus down" })
hl.bind("ALT + tab", hl.dsp.window.cycle_next({ next = true }), { description = "cycle next window" })
hl.bind("ALT + tab", hl.dsp.window.bring_to_top(), { description = "bring active to top" })

-- -----------------------------------------------------
-- 🏗️ LAYOUT CONTROLS (Master)
-- -----------------------------------------------------
hl.bind(mainMod .. " + CTRL + D", hl.dsp.layout("removemaster"), { description = "remove master" })
hl.bind(mainMod .. " + I", hl.dsp.layout("addmaster"), { description = "add master" })
hl.bind(mainMod .. " + SHIFT + Return", hl.dsp.layout("swapwithmaster"), { description = "swap with master" })

-- -----------------------------------------------------
-- 🖥️ WORKSPACE CONTROLS
-- -----------------------------------------------------
hl.bind(mainMod .. " + tab", hl.dsp.focus({ workspace = "m+1" }), { description = "next workspace" })
hl.bind(mainMod .. " + SHIFT + tab", hl.dsp.focus({ workspace = "m-1" }), { description = "previous workspace" })
hl.bind(mainMod .. " + U", hl.dsp.workspace.toggle_special(""), { description = "toggle special workspace" })
hl.bind(
	mainMod .. " + SHIFT + U",
	hl.dsp.window.move({ workspace = "special" }),
	{ description = "move to special workspace" }
)
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }), { description = "next workspace" })
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }), { description = "previous workspace" })

-- Monitor switching
hl.bind(mainMod .. " + CTRL + F9", function()
	local w = hl.get_active_workspace()
	if not w then
		return
	end
	hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "l" }))
end, { description = "move workspace to left monitor" })
hl.bind(mainMod .. " + CTRL + F10", function()
	local w = hl.get_active_workspace()
	if not w then
		return
	end
	hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "r" }))
end, { description = "move workspace to right monitor" })
hl.bind(mainMod .. " + CTRL + F11", function()
	local w = hl.get_active_workspace()
	if not w then
		return
	end
	hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "u" }))
end, { description = "move workspace to up monitor" })
hl.bind(mainMod .. " + CTRL + F12", function()
	local w = hl.get_active_workspace()
	if not w then
		return
	end
	hl.dispatch(hl.dsp.workspace.move({ workspace = w.id, monitor = "d" }))
end, { description = "move workspace to down monitor" })

-- Numeric workspace switching (1-10)
hl.bind(mainMod .. " + code:10", hl.dsp.focus({ workspace = 1 }), { description = "workspace 1" })
hl.bind(mainMod .. " + code:11", hl.dsp.focus({ workspace = 2 }), { description = "workspace 2" })
hl.bind(mainMod .. " + code:12", hl.dsp.focus({ workspace = 3 }), { description = "workspace 3" })
hl.bind(mainMod .. " + code:13", hl.dsp.focus({ workspace = 4 }), { description = "workspace 4" })
hl.bind(mainMod .. " + code:14", hl.dsp.focus({ workspace = 5 }), { description = "workspace 5" })
hl.bind(mainMod .. " + code:15", hl.dsp.focus({ workspace = 6 }), { description = "workspace 6" })
hl.bind(mainMod .. " + code:16", hl.dsp.focus({ workspace = 7 }), { description = "workspace 7" })
hl.bind(mainMod .. " + code:17", hl.dsp.focus({ workspace = 8 }), { description = "workspace 8" })
hl.bind(mainMod .. " + code:18", hl.dsp.focus({ workspace = 9 }), { description = "workspace 9" })
hl.bind(mainMod .. " + code:19", hl.dsp.focus({ workspace = 10 }), { description = "workspace 10" })

-- Move window to workspace (1-10)
hl.bind(mainMod .. " + SHIFT + code:10", hl.dsp.window.move({ workspace = 1 }), { description = "move to workspace 1" })
hl.bind(mainMod .. " + SHIFT + code:11", hl.dsp.window.move({ workspace = 2 }), { description = "move to workspace 2" })
hl.bind(mainMod .. " + SHIFT + code:12", hl.dsp.window.move({ workspace = 3 }), { description = "move to workspace 3" })
hl.bind(mainMod .. " + SHIFT + code:13", hl.dsp.window.move({ workspace = 4 }), { description = "move to workspace 4" })
hl.bind(mainMod .. " + SHIFT + code:14", hl.dsp.window.move({ workspace = 5 }), { description = "move to workspace 5" })
hl.bind(mainMod .. " + SHIFT + code:15", hl.dsp.window.move({ workspace = 6 }), { description = "move to workspace 6" })
hl.bind(mainMod .. " + SHIFT + code:16", hl.dsp.window.move({ workspace = 7 }), { description = "move to workspace 7" })
hl.bind(mainMod .. " + SHIFT + code:17", hl.dsp.window.move({ workspace = 8 }), { description = "move to workspace 8" })
hl.bind(mainMod .. " + SHIFT + code:18", hl.dsp.window.move({ workspace = 9 }), { description = "move to workspace 9" })
hl.bind(
	mainMod .. " + SHIFT + code:19",
	hl.dsp.window.move({ workspace = 10 }),
	{ description = "move to workspace 10" }
)

-- -----------------------------------------------------
-- 🛠️ SYSTEM & HARDWARE
-- -----------------------------------------------------
hl.bind("CTRL + ALT + Delete", hl.dsp.exit(), { description = "exit Hyprland" })
hl.bind("CTRL + ALT + L", hl.dsp.exec_cmd(scriptsDir .. "/LockScreen.sh"), { description = "lock screen" })
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd(scriptsDir .. "/Wlogout.sh"), { description = "powermenu" })
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("swaync-client -t -sw"), { description = "notification panel" })
hl.bind(
	mainMod .. " + SHIFT + E",
	hl.dsp.exec_cmd(scriptsDir .. "/Kool_Quick_Settings.sh"),
	{ description = "Quick settings menu" }
)
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("pkill -SIGUSR1 waybar"), { description = "toggle waybar on/off" })
hl.bind(
	"ALT_L + SHIFT_L",
	hl.dsp.exec_cmd(scriptsDir .. "/KeyboardLayout.sh switch"),
	{ locked = true, non_consuming = true, description = "switch keyboard layout globally" }
)

-- Media & Hardware Keys
hl.bind(
	"xf86audioraisevolume",
	hl.dsp.exec_cmd(scriptsDir .. "/Volume.sh --inc"),
	{ locked = true, repeating = true, description = "volume up" }
)
hl.bind(
	"xf86audiolowervolume",
	hl.dsp.exec_cmd(scriptsDir .. "/Volume.sh --dec"),
	{ locked = true, repeating = true, description = "volume down" }
)
hl.bind(
	"xf86AudioMicMute",
	hl.dsp.exec_cmd(scriptsDir .. "/Volume.sh --toggle-mic"),
	{ locked = true, description = "toggle mic mute" }
)
hl.bind("xf86Sleep", hl.dsp.exec_cmd("systemctl suspend"), { locked = true, description = "sleep" })
hl.bind(
	"xf86Rfkill",
	hl.dsp.exec_cmd(scriptsDir .. "/AirplaneMode.sh"),
	{ locked = true, description = "airplane mode" }
)
hl.bind("Print", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --swappy"), { description = "screenshot (swappy)" })

-- -----------------------------------------------------
-- 📏 RESIZE, MOVE, & SWAP (Mouse/Keyboard)
-- -----------------------------------------------------
hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.resize({ x = -50, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.resize({ x = 50, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.resize({ x = 0, y = -50, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.resize({ x = 0, y = 50, relative = true }), { repeating = true })

hl.bind(mainMod .. " + CTRL + h", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + CTRL + l", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + CTRL + k", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + CTRL + j", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + ALT + h", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + ALT + l", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + ALT + k", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + ALT + j", hl.dsp.window.swap({ direction = "d" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { description = "move window" })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { description = "resize window" })

-- -----------------------------------------------------
-- 🔄 MODAL SUBMAPS
-- -----------------------------------------------------
-- Resize Submap (Super + R)
hl.bind(mainMod .. " + R", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
	hl.bind("h", hl.dsp.window.resize({ x = -20, y = 0, relative = true }), { repeating = true })
	hl.bind("l", hl.dsp.window.resize({ x = 20, y = 0, relative = true }), { repeating = true })
	hl.bind("k", hl.dsp.window.resize({ x = 0, y = -20, relative = true }), { repeating = true })
	hl.bind("j", hl.dsp.window.resize({ x = 0, y = 20, relative = true }), { repeating = true })

	-- GTK Ad-Hoc Text Scaler
	hl.bind("equal", hl.dsp.exec_cmd(scriptsDir .. "/GtkScale.sh up"), { repeating = true })
	hl.bind("minus", hl.dsp.exec_cmd(scriptsDir .. "/GtkScale.sh down"), { repeating = true })
	hl.bind("backspace", hl.dsp.exec_cmd(scriptsDir .. "/GtkScale.sh reset"))

	hl.bind("escape", hl.dsp.submap("reset"))
	hl.bind(mainMod .. " + R", hl.dsp.submap("reset"))
end)

-- Move Submap (Super + D)
hl.bind(mainMod .. " + D", hl.dsp.submap("move"))
hl.define_submap("move", function()
	hl.bind("h", hl.dsp.window.move({ direction = "l" }))
	hl.bind("l", hl.dsp.window.move({ direction = "r" }))
	hl.bind("k", hl.dsp.window.move({ direction = "u" }))
	hl.bind("j", hl.dsp.window.move({ direction = "d" }))
	hl.bind(1, hl.dsp.window.move({ workspace = 1 }))
	hl.bind(2, hl.dsp.window.move({ workspace = 2 }))
	hl.bind(3, hl.dsp.window.move({ workspace = 3 }))
	hl.bind(4, hl.dsp.window.move({ workspace = 4 }))
	hl.bind(5, hl.dsp.window.move({ workspace = 5 }))
	hl.bind(6, hl.dsp.window.move({ workspace = 6 }))
	hl.bind(7, hl.dsp.window.move({ workspace = 7 }))
	hl.bind(8, hl.dsp.window.move({ workspace = 8 }))
	hl.bind(9, hl.dsp.window.move({ workspace = 9 }))
	hl.bind(0, hl.dsp.window.move({ workspace = 10 }))
	hl.bind("escape", hl.dsp.submap("reset"))
	hl.bind(mainMod .. " + D", hl.dsp.submap("reset"))
end)
