-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local mainMod = "SUPER"
local scriptsDir = HOME .. "/.config/hypr/scripts"
local Touchpad_Device = "asue1209:00-04f3:319f-touchpad"
local TOUCHPAD_ENABLED = true

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- See https://wiki.hyprland.org/Configuring/Keywords/ for more variable settings
-- These configs are mostly for laptops. This is addemdum to Keybinds.conf

-- for disabling Touchpad. hyprctl devices to get device name. 

-- Keyboard backlight toggle/cycle
hl.bind("XF86KbdLightOnOff", hl.dsp.exec_cmd("~/.config/hypr/scripts/BrightnessKbd.sh --inc"))
hl.bind("xf86KbdBrightnessDown", hl.dsp.exec_cmd(scriptsDir .. "/BrightnessKbd.sh --dec"), { repeating = true })
hl.bind("xf86KbdBrightnessUp", hl.dsp.exec_cmd(scriptsDir .. "/BrightnessKbd.sh --inc"), { repeating = true })
hl.bind("xf86Launch1", hl.dsp.exec_cmd("rog-control-center"))
hl.bind("xf86Launch3", hl.dsp.exec_cmd("asusctl led-mode -n"))
hl.bind("xf86Launch4", hl.dsp.exec_cmd("asusctl profile -n"))
hl.bind("xf86MonBrightnessDown", hl.dsp.exec_cmd(scriptsDir .. "/Brightness.sh --dec"), { repeating = true })
hl.bind("xf86MonBrightnessUp", hl.dsp.exec_cmd(scriptsDir .. "/Brightness.sh --inc"), { repeating = true })
hl.bind("xf86TouchpadToggle", function()
    TOUCHPAD_ENABLED = not TOUCHPAD_ENABLED
    hl.exec_cmd("hyprctl keyword device:" .. Touchpad_Device .. ":enabled " .. tostring(TOUCHPAD_ENABLED))
    local state = TOUCHPAD_ENABLED and "Enabled" or "Disabled"
    os.execute("notify-send -u low -i ~/.config/hypr/swaync/images/ja.png ' Touchpad' ' " .. state .. "'")
end)

-- Screenshot keybindings using F6 (no PrinSrc button)
hl.bind(mainMod .. " + F6", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --now"))
hl.bind(mainMod .. " + SHIFT + F6", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --area"))
hl.bind(mainMod .. " + CTRL + F6", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --in5"))
hl.bind(mainMod .. " + ALT + F6", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --in10"))
hl.bind("ALT + F6", hl.dsp.exec_cmd(scriptsDir .. "/ScreenShot.sh --active"))

hl.device({
    name = Touchpad_Device,
    enabled = TOUCHPAD_ENABLED,
})

