-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local scriptsDir = HOME .. "/.config/hypr/scripts"
local lock = scriptsDir .. "/LockScreen.sh"
local AwwwRandom = scriptsDir .. "/WallpaperAutoChange.sh"
local wallDIR = HOME .. "/Pictures/wallpapers" -- change path manually here if needed

-- /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
-- Commands and Apps to be executed at launch (vendor defaults)

--## Startup ###
--exec-once = qs -c overview  # Quickshell Overview

-- Clipboard manager

--## wallpaper stuff ###
-- Persistent wallpaper
-- exec-once = awww-daemon --format xrgb && awww img $wallDIR/mecha-nostalgia.png
-- wallpaper random

-- xdg-desktop-portal-hyprland (should be auto starting. However, you can force to start)
--exec-once = $scriptsDir/PortalHyprland.sh

-- Open browser and terminal on start
-- exec-once = [workspace 1 silent] brave
-- exec-once = [workspace 2 silent] kitty

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("$HOME/.config/hypr/scripts/Dropterminal.sh kitty &")
    hl.exec_cmd(scriptsDir .. "/Polkit.sh")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("swaync -c ~/.config/hypr/swaync/config.json")
    -- Rainbow Borders natively
    local function random_hex()
        return string.format("0xff%06x", math.random(0, 0xFFFFFF))
    end
    local color_str = ""
    for i=1, 10 do
        color_str = color_str .. random_hex() .. " "
    end
    hl.exec_cmd("hyprctl keyword general:col.active_border " .. color_str .. " 270deg")
    hl.exec_cmd("rog-control-center")
    hl.exec_cmd("waybar -c ~/.config/hypr/waybar/config.jsonc -s ~/.config/hypr/waybar/style.css &")
    hl.exec_cmd("hypridle")
    hl.exec_cmd(scriptsDir .. "/Hyprsunset.sh daemon &")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd(AwwwRandom .. " " .. wallDIR)
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("ags")
    hl.exec_cmd(scriptsDir .. "/KeybindsLayoutInit.sh")
end)

