# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(131416)
$foreground = rgb(EBE2E3)
$color0 = rgb(3A3C3E)
$color1 = rgb(091017)
$color2 = rgb(4E3C40)
$color3 = rgb(4E3C40)
$color4 = rgb(4E3C40)
$color5 = rgb(4E3C40)
$color6 = rgb(948183)
$color7 = rgb(DACDCF)
$color8 = rgb(989091)
$color9 = rgb(0C151E)
$color10 = rgb(685055)
$color11 = rgb(685055)
$color12 = rgb(685055)
$color13 = rgb(685055)
$color14 = rgb(C5ACAF)
$color15 = rgb(DACDCF)
