# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(171717)
$foreground = rgb(F6E1C9)
$color0 = rgb(3E3E3E)
$color1 = rgb(131618)
$color2 = rgb(57362A)
$color3 = rgb(2E424F)
$color4 = rgb(793075)
$color5 = rgb(3C596A)
$color6 = rgb(AC7E4C)
$color7 = rgb(EACBAA)
$color8 = rgb(A38E77)
$color9 = rgb(1A1D20)
$color10 = rgb(744838)
$color11 = rgb(3E5869)
$color12 = rgb(A1409C)
$color13 = rgb(50768E)
$color14 = rgb(E5A865)
$color15 = rgb(EACBAA)
