# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141414)
$foreground = rgb(F5F7FB)
$color0 = rgb(3B3C3B)
$color1 = rgb(0D100D)
$color2 = rgb(0D100D)
$color3 = rgb(294531)
$color4 = rgb(364650)
$color5 = rgb(596D7E)
$color6 = rgb(AAAFB7)
$color7 = rgb(E8ECF1)
$color8 = rgb(A2A5A9)
$color9 = rgb(121511)
$color10 = rgb(121511)
$color11 = rgb(365C41)
$color12 = rgb(485D6A)
$color13 = rgb(7791A8)
$color14 = rgb(E2E9F4)
$color15 = rgb(E8ECF1)
